### PR TITLE
Fixed HL Laoding due to background size  #21

### LINKED ISSUE #21: Background Image not working for HL
When starting the application the HL Leagues cannot start a game due to the new background color definitions being global in the GameController

### PR DESCRIPTION
**Pull request by sheepsy90robocup**
Fixes #21 
Added unittesting

### CODE REVIEW

**Comment by sheepsy90robocup** [comment]
Fixed the conflict - this branch is now ready to merge

**Comment by bhuman** [comment]
Thanks for contributing to the GameController.

However, the patch completely breaks the Start dialog. Before, no "Color" buttons were shown for the Humanoid League and the default color for the right team was red (magenta). Now the dialog starts with both teams having the same color. Before, if a right team is selected, it would automatically choose the color that is different from the first team.

The warning text at the bottom is not really stylish and to show a red text below the main dialog button is an unusual choice in interface design.

So far, the core GameController follows the rule not to have setters and getters unless they provide actual functionality.

**Comment by sheepsy90** [comment]
The colors for the humanoid league are actually intentionally - yes maybe they should be different from the beginning, but then the league has the possibility to have different colors.

The problem with the non setters and getters is that this type of architecture is horrible to test and verify functionality.

Given the color change. Would the change be merged?

**Comment by bhuman** [comment]
Maybe we start from the beginning: Which changes in the GameController does the Humanoid League need to make it compliant with the rulebook for RoboCup 2017?

**Comment by sheepsy90** [comment]
I don't know yet. Maike Paetzel (HL TC) asked me to familiarize myself with the GC to merge divergent branches between the HL one and the original one, and later implement some other things for the HL.

I checked out the code and tried to understand it. First thing I noticed was no Unit testing at all. So I added those. But by doing so I understood why there are no unit tests. It is difficult and the architecture doesn't really support testing as it is one single static thing.

This is why I changed the Start page to be not that paradigm anymore and have it more Object Oriented. This allows us to have a high coding standard.

I need also disagree with the getters and setters. Yes if there is just a data holding object they might be useless but they also provide a backwards compatible interface so why go through this direct pointer issue when they can be useful.

**Comment by bhuman** [comment]
So we wait until it is clear which changes are necessary, then it is checked how this can be implemented with minimal effort, then they are implemented, and then we test whether everything still works.

Currently, the pull request does not work, because it breaks existing functionality. 

The original issue was solved by changing a single line of code (the second one was not really necessary, but it was more constistent to change both).

About testing: The GameController is a complex piece of software and automatic testing would be very useful. However, testing only makes sense for the complex parts of the software, i.e. the mapping "(state, event) -> expectedState", e.g. does a button press really have the desired effect on all the user interface elements and what is sent to the robots? These kinds of tests also make a lot of sense because they are very different from how the GameController internally works, where each UI elements evaluates its current state by itself based on the central model. Such tests would also reveal whether changes made for one league break the support for the other leagues.

To check whether an `equals` method works (that is not necessary, because the rules are singletons and their addresses identify them perfectly) is not the kind of test that is useful for this kind of application.

**Pull request closed without merging**
