### PR TITLE
Allow Substitution of Player One

### PR DESCRIPTION
**Pull request by felixwege**
This PR allows player one to be substituted.

### CODE REVIEW

**Comment by bhuman** [comment]
The rules say: Goal Keeper ... It always has the jersey number "1".

Since substitution is a change of the player number, how can this be legal?

**Comment by felixwege** [comment]
I do not think it is illegal to substitute the 1. The substitute would be a regular field player without the rights of a keeper.

**Comment by bhuman** [comment]
Yes that might be true, but it is quite confusing. Why giving up the privileges of a goal keeper when you can simple switch the jersey and bring a different robot in as the goal keeper?

In addition, the rules do not really support five field players, because Figure 9 in the rulebook does not show manual placement positions for them.

**Comment by bhuman** [comment]
Closed because the TC has decided that this should not be legal.

**Pull request closed without merging**
